novo_testamento1 = {
    "evangelho segundo s. mateus": "https://vulgata.online/bible/Mt",
    "evangelho segundo s. marcos": "https://vulgata.online/bible/Mc",
    "evangelho segundo s. lucas": "https://vulgata.online/bible/Lc",
    "evangelho segundo s. joão": "https://vulgata.online/bible/Jo",
    "actos dos apóstolos": "https://vulgata.online/bible/Act",
    "epístola aos romanos": "https://vulgata.online/bible/Rm",
    "primeira epístola aos coríntios": "https://vulgata.online/bible/1Co",
    "segunda epístola aos coríntios": "https://vulgata.online/bible/2Co",
    "epístola aos gálatas": "https://vulgata.online/bible/Gl",
    "epístola aos efésios": "https://vulgata.online/bible/Ef",
    "epístola aos filipenses": "https://vulgata.online/bible/Fp",
    "epístola aos colossenses": "https://vulgata.online/bible/Cl",
    "primeira epístola aos tessalonicenses": "https://vulgata.online/bible/1Ts",
    "segunda epístola aos tessalonicenses": "https://vulgata.online/bible/2Ts",
    "primeira epístola a timóteo": "https://vulgata.online/bible/1Tm",
    "segunda epístola a timóteo": "https://vulgata.online/bible/2Tm",
    "epístola a títo": "https://vulgata.online/bible/Tt",
    "epístola a filêmon": "https://vulgata.online/bible/Fm",
    "epístola aos hebreus": "https://vulgata.online/bible/Hb",
    "epístola de s. tiago": "https://vulgata.online/bible/Tg",
    "primeira epístola de s. pedro": "https://vulgata.online/bible/1Pe",
    "segunda epístola de s. pedro": "https://vulgata.online/bible/2Pe",
    "primeira epístola de s. joão": "https://vulgata.online/bible/1Jo",
    "segunda epístola de s. joão": "https://vulgata.online/bible/2Jo",
    "terceira epístola de s. joão": "https://vulgata.online/bible/3Jo",
}