antigo_testamento2 = {
    "eclesiástico": "https://vulgata.online/bible/Eus",
    "profecia de isaías": "https://vulgata.online/bible/Is",
    "profecia de jeremias": "https://vulgata.online/bible/Je",
    "trenos ou lamentações de jeremias": "https://vulgata.online/bible/Lm",
    "profecia de baruch": "https://vulgata.online/bible/Ba",
    "profecia de ezequiel": "https://vulgata.online/bible/Ez",
    "profecia de daniel": "https://vulgata.online/bible/Dn",
    "oseias": "https://vulgata.online/bible/Os",
    "profecia de joel": "https://vulgata.online/bible/Jl",
    "profecia de amós": "https://vulgata.online/bible/Am",
    "profecia de abdias": "https://vulgata.online/bible/Ab",
    "profecia de jonas": "https://vulgata.online/bible/Jn",
    "profecia de miqueias": "https://vulgata.online/bible/Mic",
    "profecia de naum": "https://vulgata.online/bible/Na",
    "profecia de habucuc": "https://vulgata.online/bible/Hc",
    "profecia de sofonias": "https://vulgata.online/bible/So",
    "profecia de ageu": "https://vulgata.online/bible/Ag",
    "profecia de zacarias": "https://vulgata.online/bible/Zc",
    "profecia de malaquias": "https://vulgata.online/bible/Ml",
    "livro primeiro dos macabeus": "https://vulgata.online/bible/1Ma",
    "livro segundo dos macabeus": "https://vulgata.online/bible/2Ma",
}