antigo_testamento1 = {
    "gênesis": "https://vulgata.online/bible/Gn",
    "êxodo": "https://vulgata.online/bible/Ex",
    "levítico": "https://vulgata.online/bible/Lv",
    "números": "https://vulgata.online/bible/Nm",
    "deuteronômio": "https://vulgata.online/bible/Dt",
    "livro de josué": "https://vulgata.online/bible/Js",
    "livro dos juízes": "https://vulgata.online/bible/Ju",
    "livro de rute": "https://vulgata.online/bible/Rt",
    "livro primeiro de samuel": "https://vulgata.online/bible/1Sm",
    "livro segundo de samuel": "https://vulgata.online/bible/2Sm",
    "livro primeiro dos reis": "https://vulgata.online/bible/1Rs",
    "livro segundo dos reis": "https://vulgata.online/bible/2Rs",
    "livro primeiro das crônicas": "https://vulgata.online/bible/1Pa",
    "livro segundo das crônicas": "https://vulgata.online/bible/2Pa",
    "livro de esdras": "https://vulgata.online/bible/Esd",
    "livro de neemias": "https://vulgata.online/bible/Ne",
    "livro de tobias": "https://vulgata.online/bible/Tob",
    "livro de judit": "https://vulgata.online/bible/Jdi",
    "livro de ester": "https://vulgata.online/bible/Est",
    "livro de job": "https://vulgata.online/bible/Job",
    "salmos": "https://vulgata.online/bible/Ps",
    "livro dos provérbios": "https://vulgata.online/bible/Pv",
    "livro do eclesiaste": "https://vulgata.online/bible/Ees",
    "cânticos dos cânticos": "https://vulgata.online/bible/Cc",
    "livro da sabedoria": "https://vulgata.online/bible/Sa",
}